config-pin: dont touch the slots file if bone_capemgr.uboot_capemgr_enabled is set
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

diff --git a/tools/beaglebone-universal-io/config-pin b/tools/beaglebone-universal-io/config-pin
--- a/tools/beaglebone-universal-io/config-pin
+++ b/tools/beaglebone-universal-io/config-pin
@@ -26,6 +26,7 @@ TI_AM335x_BeagleBone_Blue)
 	;;
 esac
 
+disable_capemgr_load=$(grep -c bone_capemgr.uboot_capemgr_enabled=1 /proc/cmdline)
 
 # Create mappings between BeagleBone header pins and kernel gpio
 # numbers.  These could be bash arrays or coded in python, but simple
@@ -888,16 +889,17 @@ load_cape () {
 		# Make sure required device tree overlay(s) are loaded
 		# cape-bone-iio
 		for DTBO in $1 ; do
-
-			if grep -q $DTBO $SLOTS ; then
-				echo_std $DTBO already loaded
-			else
-				# Expand filename using shell globbing
-				for FILE in $SLOTS ; do
-					echo_std Loading $DTBO overlay
-					sudo -A bash -c "echo $DTBO > $SLOTS" || (echo_err "Error loading device tree overlay file: $DTBO" && exit 1)
-					sleep 1
-				done
+			if [ ! ${disable_capemgr_load} ] ; then
+				if grep -q $DTBO $SLOTS ; then
+					echo_std $DTBO already loaded
+				else
+					# Expand filename using shell globbing
+					for FILE in $SLOTS ; do
+						echo_std Loading $DTBO overlay
+						sudo -A bash -c "echo $DTBO > $SLOTS" || (echo_err "Error loading device tree overlay file: $DTBO" && exit 1)
+						sleep 1
+					done
+				fi
 			fi
 		done;
 	fi
@@ -917,19 +919,21 @@ check_pin () {
 		# use only first overlay
 		CAPE=`echo "$CAPE" | cut -d' ' -f1`
 
-		if [ -d $SLOTS ] ; then
-			if [ $AUTOLOAD -eq 0 ] ; then
-				if grep -q $CAPE $SLOTS ; then
-					echo_err "$CAPE already loaded"
-					echo_err "Please verify your device tree file"
+		if [ ! ${disable_capemgr_load} ] ; then
+			if [ -d $SLOTS ] ; then
+				if [ $AUTOLOAD -eq 0 ] ; then
+					if grep -q $CAPE $SLOTS ; then
+						echo_err "$CAPE already loaded"
+						echo_err "Please verify your device tree file"
+					else
+						echo_err "$CAPE overlay not found"
+						echo_err "run \"$(basename $0) overlay $CAPE\" to load the cape"
+					fi
+					exit 1
 				else
-					echo_err "$CAPE overlay not found"
-					echo_err "run \"$(basename $0) overlay $CAPE\" to load the cape"
+					echo_std $1 overlay not found
+					load_cape $CAPE
 				fi
-				exit 1
-			else
-				echo_std $1 overlay not found
-				load_cape $CAPE
 			fi
 		fi
 	fi
