config-pin: we no longer need sudo access for pinmux, root:gpio permissions
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

diff --git a/tools/beaglebone-universal-io/config-pin b/tools/beaglebone-universal-io/config-pin
--- a/tools/beaglebone-universal-io/config-pin
+++ b/tools/beaglebone-universal-io/config-pin
@@ -1015,7 +1015,11 @@ config_pin () {
 			eval GPIO="\$${PIN}_GPIO"
 			FILE="$GPIODIR/gpio$GPIO/direction"
 			if [ -e $FILE ] ; then
-				sudo -A bash -c "echo $DIR > $FILE" || (echo_err "Cannot write gpio direction file: $FILE" && exit 1)
+				if [ -w $FILE ] ; then
+					echo $DIR > $FILE || (echo_err "Cannot write gpio direction file: $FILE" && exit 1)
+				else
+					sudo -A bash -c "echo $DIR > $FILE" || (echo_err "Cannot write gpio direction file: $FILE" && exit 1)
+				fi
 			else
 				echo_err "WARNING: GPIO pin not exported, cannot set direction or value!"
 			fi
@@ -1025,13 +1029,21 @@ config_pin () {
 			# Expand filename using shell globbing
 			for FILE in $OCPDIR${PIN}_pinmux/state ; do
 				echo_dbg "echo $MODE > $FILE"
-				sudo -A bash -c "echo $MODE > $FILE" || (echo_err "Cannot write pinmux file: $FILE" && exit 1)
+				if [ -w $FILE ] ; then
+					echo $MODE > $FILE || (echo_err "Cannot write pinmux file: $FILE" && exit 1)
+				else
+					sudo -A bash -c "echo $MODE > $FILE" || (echo_err "Cannot write pinmux file: $FILE" && exit 1)
+				fi
 			done
 		else
 			# Expand filename using shell globbing
 			for FILE in $OCPDIR/${PIN}_pinmux.*/state ; do
 				echo_dbg "echo $MODE > $FILE"
-				sudo -A bash -c "echo $MODE > $FILE" || (echo_err "Cannot write pinmux file: $FILE" && exit 1)
+				if [ -w $FILE ] ; then
+					echo $MODE > $FILE || (echo_err "Cannot write pinmux file: $FILE" && exit 1)
+				else
+					sudo -A bash -c "echo $MODE > $FILE" || (echo_err "Cannot write pinmux file: $FILE" && exit 1)
+				fi
 			done
 		fi
 	fi
